/*
 * Deep Lynx
 *
 * The construction of megaprojects has consistently demonstrated challenges for project managers in regard to meeting cost, schedule, and performance requirements. Megaproject construction challenges are common place within megaprojects with many active projects in the United States failing to meet cost and schedule efforts by significant margins. Currently, engineering teams operate in siloed tools and disparate teams where connections across design, procurement, and construction systems are translated manually or over brittle point-to-point integrations. The manual nature of data exchange increases the risk of silent errors in the reactor design, with each silent error cascading across the design. These cascading errors lead to uncontrollable risk during construction, resulting in significant delays and cost overruns. Deep Lynx allows for an integrated platform during design and operations of mega projects. The Deep Lynx Core API delivers a few main features. 1. Provides a set of methods and endpoints for manipulating data in an object oriented database. This allows us to store complex datatypes as records and then to compile them into actual, modifiable objects at run-time. Users can store taxonomies or ontologies in a readable format. 2. Provides methods for storing and retrieving data in a graph database. This data is structured and validated against the aformentioned object oriented database before storage.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileInfo {
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "file_name")]
    pub file_name: String,
    #[serde(rename = "file_size", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<f32>,
    #[serde(rename = "adapter_file_path")]
    pub adapter_file_path: String,
    #[serde(rename = "adapter", skip_serializing_if = "Option::is_none")]
    pub adapter: Option<String>,
    #[serde(rename = "data_source_id")]
    pub data_source_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<String>,
    #[serde(rename = "created_by")]
    pub created_by: String,
    #[serde(rename = "modified_by", skip_serializing_if = "Option::is_none")]
    pub modified_by: Option<String>,
    #[serde(rename = "container_id")]
    pub container_id: String,
    #[serde(rename = "md5hash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub md5hash: Option<Option<String>>,
    #[serde(rename = "short_uuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub short_uuid: Option<Option<String>>,
}

impl FileInfo {
    pub fn new(id: String, file_name: String, adapter_file_path: String, data_source_id: String, created_at: String, created_by: String, container_id: String) -> FileInfo {
        FileInfo {
            metadata: None,
            id,
            file_name,
            file_size: None,
            adapter_file_path,
            adapter: None,
            data_source_id,
            created_at,
            modified_at: None,
            created_by,
            modified_by: None,
            container_id,
            md5hash: None,
            short_uuid: None,
        }
    }
}


