/*
 * Deep Lynx
 *
 * The construction of megaprojects has consistently demonstrated challenges for project managers in regard to meeting cost, schedule, and performance requirements. Megaproject construction challenges are common place within megaprojects with many active projects in the United States failing to meet cost and schedule efforts by significant margins. Currently, engineering teams operate in siloed tools and disparate teams where connections across design, procurement, and construction systems are translated manually or over brittle point-to-point integrations. The manual nature of data exchange increases the risk of silent errors in the reactor design, with each silent error cascading across the design. These cascading errors lead to uncontrollable risk during construction, resulting in significant delays and cost overruns. Deep Lynx allows for an integrated platform during design and operations of mega projects. The Deep Lynx Core API delivers a few main features. 1. Provides a set of methods and endpoints for manipulating data in an object oriented database. This allows us to store complex datatypes as records and then to compile them into actual, modifiable objects at run-time. Users can store taxonomies or ontologies in a readable format. 2. Provides methods for storing and retrieving data in a graph database. This data is structured and validated against the aformentioned object oriented database before storage.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceUser {
    #[serde(rename = "identity_provider")]
    pub identity_provider: String,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "admin")]
    pub admin: bool,
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "reset_required")]
    pub reset_required: bool,
    #[serde(rename = "email_valid")]
    pub email_valid: bool,
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<serde_json::Value>>,
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Vec<serde_json::Value>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "identity_provider_id")]
    pub identity_provider_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at")]
    pub modified_at: String,
    #[serde(rename = "created_by")]
    pub created_by: String,
    #[serde(rename = "modified_by")]
    pub modified_by: String,
    #[serde(rename = "reset_token_issued")]
    pub reset_token_issued: String,
    #[serde(rename = "keys", skip_serializing_if = "Option::is_none")]
    pub keys: Option<Vec<crate::models::ServiceUserKeysInner>>,
}

impl ServiceUser {
    pub fn new(identity_provider: String, display_name: String, email: String, admin: bool, active: bool, reset_required: bool, email_valid: bool, id: String, identity_provider_id: String, created_at: String, modified_at: String, created_by: String, modified_by: String, reset_token_issued: String) -> ServiceUser {
        ServiceUser {
            identity_provider,
            display_name,
            email,
            admin,
            active,
            reset_required,
            email_valid,
            permissions: None,
            roles: None,
            id,
            identity_provider_id,
            created_at,
            modified_at,
            created_by,
            modified_by,
            reset_token_issued,
            keys: None,
        }
    }
}


